INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = webTweakTest

webTweakTest_FILES = Tweak.x
webTweakTest_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
